#!/bin/bash

# Due to limitations of Composer, create a temporary branch
commit="tmp-$(git rev-parse --verify HEAD)"
git checkout -b $commit

# Create Laravel project
composer create-project --prefer-dist laravel/laravel test-app
cd test-app

# Scaffold Authentication
php artisan make:auth

# Require the package
composer config repositories.dczajkowski/auth-tests vcs $GITHUB_WORKSPACE
composer require dczajkowski/auth-tests dev-$commit
