name: 'Run tests on Laravel'

on:
  pull_request:
    branches:
    - master
  schedule:
    - cron: '0 8 * * *'

jobs:
  test_without_email_verification:
    name: (PHP ${{ matrix.php }}, Laravel 8) Tests without email verification
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.3', '7.4']

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Installs PHP version ${{ matrix.php }}
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php }}

    - name: 'Verifies environment'
      run: |
        php -v
        composer --version

    - name: 'Sets up tests'
      run: /bin/bash -e $GITHUB_WORKSPACE/.github/actions/tests-without-email-verification

    - name: 'Runs tests'
      run: ( cd test-app && ./vendor/bin/phpunit )

  test_with_email_verification:
    name: (PHP ${{ matrix.php }}, Laravel 8) Tests with email verification
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.3', '7.4']

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Installs PHP version ${{ matrix.php }}
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php }}

    - name: 'Verifies environment'
      run: |
        php -v
        composer --version

    - name: 'Sets up tests'
      run: /bin/bash -e $GITHUB_WORKSPACE/.github/actions/tests-with-email-verification

    - name: 'Runs tests'
      run: ( cd test-app && ./vendor/bin/phpunit )
